In [68]:
import traceback


def green(s):
    return '\033[1;32m%s\033[m' % s


def yellow(s):
    return '\033[1;33m%s\033[m' % s


def red(s):
    return '\033[1;31m%s\033[m' % s


def log(*m):
    print(" ".join(map(str, m)))


def log_exit(*m):
    log(red("ERROR:"), *m)
    exit(1)


def check_numpy():
    try:
        import numpy
        log(green("PASS"), "NumPy installed")
    except ModuleNotFoundError:
        log(red("FAIL"), "NumPy not installed")


def check_scipy():
    try:
        import scipy
        log(green("PASS"), "SciPy installed")
    except ModuleNotFoundError:
        log(red("FAIL"), "SciPy not installed")


def check_matplotlib():
    try:
        import matplotlib
        log(green("PASS"), "matplotlib installed")
    except ModuleNotFoundError:
        log(red("FAIL"), "matplotlib not installed")


def check_torch():
    try:
        import torch
        log(green("PASS"), "PyTorch installed")
    except ModuleNotFoundError:
        log(red("FAIL"), "PyTorch not installed")


def check_tqdm():
    try:
        import tqdm
        log(green("PASS"), "tqdm installed")
    except ModuleNotFoundError:
        log(red("FAIL"), "tqdm not installed")


def main():
    try:
        check_numpy()
        check_scipy()
        check_matplotlib()
        check_torch()
        check_tqdm()
    except Exception:
        log_exit(traceback.format_exc())


if __name__ == "__main__":
    main()

PASS NumPy installed
PASS SciPy installed
PASS matplotlib installed
PASS PyTorch installed
PASS tqdm installed


In [69]:
import numpy as np

In [70]:
def randomization(n):
    """
    Arg:
      n - an integer
    Returns:
      A - a randomly-generated nx1 Numpy array.
    """
    #Your code here
    A = np.random.random(size=n).reshape(n,1)
    return A

In [71]:
z = randomization(5)
print (z)

[[0.11594155]
 [0.52459804]
 [0.58612944]
 [0.08501943]
 [0.9647979 ]]


In [72]:
def operations(h, w):
    """
    Takes two inputs, h and w, and makes two Numpy arrays A and B of size
    h x w, and returns A, B, and s, the sum of A and B.

    Arg:
      h - an integer describing the height of A and B
      w - an integer describing the width of A and B
    Returns (in this order):
      A - a randomly-generated h x w Numpy array.
      B - a randomly-generated h x w Numpy array.
      s - the sum of A and B.
    """
    #Your code here
    A = np.random.random(size=(h,w))
    B = np.random.random(size=(h,w))
    s = A + B 
    
    return A, B, s
    

In [88]:
operations(2,3)

(array([[0.33345701, 0.85557805, 0.42426876],
        [0.36991492, 0.48726608, 0.41012965]]),
 array([[0.1343311 , 0.29827966, 0.90605467],
        [0.69045599, 0.76656205, 0.07071967]]),
 array([[0.46778811, 1.1538577 , 1.33032344],
        [1.06037091, 1.25382813, 0.48084932]]))

In [74]:
def norm(A, B):
    """
    Takes two Numpy column arrays, A and B, and returns the L2 norm of their
    sum.

    Arg:
      A - a Numpy array
      B - a Numpy array
    Returns:
      s - the L2 norm of A+B.
    """
    #Your code here
    s = A + B
    
    return np.linalg.norm(s)

In [75]:
A = randomization(2)
B = randomization(2)
norm(A,B)

0.990203866119657

In [76]:
def neural_network(inputs, weights):
    """
     Takes an input vector and runs it through a 1-layer neural network
     with a given weight matrix and returns the output.

     Arg:
       inputs - 2 x 1 NumPy array
       weights - 2 x 1 NumPy array
     Returns (in this order):
       out - a 1 x 1 NumPy array, representing the output of the neural network
    """
    #Your code here
    z = np.tanh(weights.T.dot(inputs))
    
    return z

In [77]:
inputs = randomization(2)
print(inputs)

[[0.77412912]
 [0.51316132]]


In [78]:
weights = randomization(2)
print(weights)

[[0.95503124]
 [0.82545794]]


In [79]:
neural_network(inputs, weights)

array([[0.82198616]])

In [80]:
def scalar_function(x, y):
    """
    Returns the f(x,y) defined in the problem statement.
    """
    #Your code here
    if (x <= y):
        return x*y
    else:
        return x/y

In [81]:
scalar_function(3,5)

15

In [82]:
scalar_function(5,3)

1.6666666666666667

In [83]:
def vector_function(x, y):
    """
    Make sure vector_function can deal with vector input x,y 
    """
    #Your code here
    output = np.vectorize(scalar_function)
    return output(x,y)

In [84]:
vector_function(3,5)

array(15)

In [85]:
vector_function(5,3)

array(1.66666667)